service: gb-challenge-ecr

provider:
  name: aws
  runtime: nodejs12.x
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}"
  stage: ${{opt:stage, self:custom.defaultStage}}
  region: ${{opt:region, self:custom.defaultRegion}}
  profile: ${{opt:aws-profile, self:custom.profiles.${{self:provider.stage}}}}
  environment:
    NODE_ENV: ${{self:provider.stage}}
    STACK_PREFIX: ${{self:service}}-${{self:provider.stage}}

plugins:
  - serverless-cloudformation-changesets

resources:
  Outputs:
    FlaskjamRepositoryName:
      Value:
        Ref: FlaskjamECRRepository
    FlaskjamRepositoryArn:
      Value:
        Fn::GetAtt: [FlaskjamECRRepository, Arn]
    ExpressjamRepositoryName:
      Value:
        Ref: ExpressjamECRRepository
    ExpressjamRepositoryArn:
      Value:
        Fn::GetAtt: [ExpressjamECRRepository, Arn]
    ECRAccountUri:
      Value: {"Fn::Sub": "${AWS::AccountId}.dkr.ecr.${{self:provider.region}}.amazonaws.com"}
  Resources:
    FlaskjamECRRepository:
      Type: AWS::ECR::Repository
      # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html
      Properties:
        RepositoryName: flaskjam-${{self:provider.stage}}
        Tags:
          - Key: stage
            Value: ${{self:provider.stage}}
    ExpressjamECRRepository:
      Type: AWS::ECR::Repository
      # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html
      Properties:
        RepositoryName: expressjam-${{self:provider.stage}}
        Tags:
          - Key: stage
            Value: ${{self:provider.stage}}


custom:
  # Custom staging profiles. You may access or modify these credentials in ~/.aws/credentials
  # See link for credentials documentation:
  #     https://serverless.com/framework/docs/providers/aws/guide/credentials/
  defaultStage: dev
  defaultRegion: ap-northeast-1
  profiles:
    production: gobear
    development: gobear

  accountId: ${AWS::AccountId}
