service: gb-challenge-app

provider:
  name: aws
  runtime: nodejs12.x
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}"
  stage: ${{opt:stage, self:custom.defaultStage}}
  region: ${{opt:region, self:custom.defaultRegion}}
  profile: ${{opt:aws-profile, self:custom.profiles.${{self:provider.stage}}}}
  environment:
    NODE_ENV: ${{self:provider.stage}}
    STACK_PREFIX: ${{self:service}}-${{self:provider.stage}}

resources:
  Outputs:
    Nothing:
      Value: "I am an empty stack"
  Resources:
    EcsTaskExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2008-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: "ecs-tasks.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: AmazonECSTaskExecutionRolePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Sid: ECSAllowECRAndLogs
                  Effect: Allow
                  Action:
                    - ecr:GetAuthorizationToken
                    - ecr:BatchCheckLayerAvailability
                    - ecr:GetDownloadUrlForLayer
                    - ecr:BatchGetImage
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"

custom:
  # Custom staging profiles. You may access or modify these credentials in ~/.aws/credentials
  # See link for credentials documentation:
  #     https://serverless.com/framework/docs/providers/aws/guide/credentials/
  defaultStage: dev
  defaultRegion: ap-northeast-1
  profiles:
    production: gobear
    development: gobear

  accountId: ${AWS::AccountId}
